#!/usr/bin/env -S pnpm exec tsx
/**
 * Read-only contract probe runner.
 *
 *   pnpm probe                 # run every probe set with credentials, write probe-snapshots/*.json
 *   pnpm probe:check           # run, compare with the committed snapshots, exit 1 on drift
 *   pnpm probe -- --only trendyol
 *
 * Flags
 *   --check                 compare fresh shapes with probe-snapshots/ instead of writing them
 *   --update                write probe-snapshots/ (default when --check is absent)
 *   --only <marketplace>    restrict to one marketplace (repeatable)
 *   --out-dir <dir>         where fresh results + report go (default: probe-output/, gitignored)
 *   --require-credentials   exit 2 when a selected marketplace has no credentials (CI guard)
 *
 * Exit codes: 0 no drift, 1 drift detected (--check), 2 usage / credential / internal error.
 *
 * Credentials come from the environment (`.env` locally via `tsx --env-file`,
 * repository secrets in CI). A marketplace whose credentials are absent is
 * *skipped*, not failed. Nothing but key names and JSON types is ever written.
 *
 * Each probe records two shapes: `shape`, the SDK's normalised return value,
 * and `wire`, every HTTP exchange the call caused (operation matched against
 * specs/, status, content type, shape of the raw JSON body). `--check` diffs
 * both and reports wire drift separately; `pnpm drift` compares `wire` with
 * the specs.
 */
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { parseArgs } from 'node:util';
import {
  buildOperationIndex,
  createWireRecorder,
  diffWire,
  isUnmatched,
  loadSpecs,
  withGlobalFetch,
  type WireDiff,
  type WireExchange,
} from '@lonca/drift';
import { hepsiburadaProbes } from './probes/hepsiburada.mts';
import { trendyolProbes } from './probes/trendyol.mts';
import {
  hasCredentials,
  runProbe,
  skippedResult,
  type Marketplace,
  type ProbeResult,
  type ProbeSet,
} from './registry.mts';
import {
  DEFAULT_SUMMARIZE_OPTIONS,
  describe,
  diffShapes,
  type Shape,
  type ShapeDiff,
} from './shape.mts';

// ─── CLI ────────────────────────────────────────────────────────────────────

const { values: flags } = parseArgs({
  options: {
    check: { type: 'boolean', default: false },
    update: { type: 'boolean', default: false },
    only: { type: 'string', multiple: true },
    'out-dir': { type: 'string', default: 'probe-output' },
    'require-credentials': { type: 'boolean', default: false },
    help: { type: 'boolean', short: 'h', default: false },
  },
  strict: true,
});

if (flags.help) {
  console.log(readFileSync(fileURLToPath(import.meta.url), 'utf8').split('*/')[0]);
  process.exit(0);
}

const REPO_ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..', '..');
const SNAPSHOT_DIR = join(REPO_ROOT, 'probe-snapshots');
const OUT_DIR = resolve(process.cwd(), flags['out-dir']);
const MODE: 'check' | 'update' = flags.check ? 'check' : 'update';

// eslint-disable-next-line @typescript-eslint/no-explicit-any -- heterogeneous client types are erased at the registry boundary
const ALL_SETS: ProbeSet<any>[] = [hepsiburadaProbes, trendyolProbes];
const selected = flags.only?.length
  ? ALL_SETS.filter((s) => flags.only!.includes(s.marketplace))
  : ALL_SETS;

if (selected.length === 0) {
  console.error(
    `✖ --only matched nothing. Known marketplaces: ${ALL_SETS.map((s) => s.marketplace).join(', ')}`,
  );
  process.exit(2);
}

// ─── Snapshot format ────────────────────────────────────────────────────────

/** Per-probe entry as committed. Timing is left out so re-runs are byte-stable. */
interface SnapshotProbe {
  status: ProbeResult['status'];
  httpStatus?: number;
  errorName?: string;
  errorCode?: string;
  /** Shape of the SDK's normalised return value. */
  shape?: Shape;
  /** Wire exchanges (raw responses) the probe caused. Absent in snapshots taken before wire capture. */
  wire?: WireExchange[];
}

interface Snapshot {
  $comment: string;
  marketplace: Marketplace;
  env: string;
  shapeOptions: typeof DEFAULT_SUMMARIZE_OPTIONS;
  probes: Record<string, SnapshotProbe>;
}

function toSnapshot(set: ProbeSet<unknown>, results: ProbeResult[]): Snapshot {
  const probes: Record<string, SnapshotProbe> = {};
  for (const r of [...results].sort((a, b) => a.name.localeCompare(b.name))) {
    const entry: SnapshotProbe = { status: r.status };
    if (r.httpStatus !== undefined) entry.httpStatus = r.httpStatus;
    if (r.errorName !== undefined) entry.errorName = r.errorName;
    if (r.errorCode !== undefined) entry.errorCode = r.errorCode;
    if (r.shape !== undefined) entry.shape = r.shape;
    if (r.wire !== undefined) entry.wire = r.wire;
    probes[r.name] = entry;
  }
  return {
    $comment:
      'Structural snapshot generated by scripts/probe/run.mts — key sets and JSON types only, never values; wire paths are spec templates or redacted. Regenerate with `pnpm probe`.',
    marketplace: set.marketplace,
    env: set.envLabel(),
    shapeOptions: DEFAULT_SUMMARIZE_OPTIONS,
    probes,
  };
}

function readSnapshot(marketplace: Marketplace): Snapshot | undefined {
  const file = join(SNAPSHOT_DIR, `${marketplace}.json`);
  if (!existsSync(file)) return undefined;
  return JSON.parse(readFileSync(file, 'utf8')) as Snapshot;
}

function writeJson(file: string, value: unknown): void {
  mkdirSync(dirname(file), { recursive: true });
  writeFileSync(file, `${JSON.stringify(value, null, 2)}\n`, 'utf8');
}

// ─── Drift detection ────────────────────────────────────────────────────────

interface ProbeDrift {
  probe: string;
  /** Probe-level changes (status / http / error code). Always drift. */
  statusChanges: string[];
  /** Structural changes. `nullability` entries are informational. */
  shapeDiffs: ShapeDiff[];
  /** Raw wire changes (`{ baseline: 'missing' }` for snapshots taken before wire capture). */
  wire: WireDiff;
}

const NO_WIRE_CHANGE: WireDiff = { baseline: 'present', changes: [], shapeDiffs: [] };

function driftFor(before: Snapshot | undefined, after: Snapshot): ProbeDrift[] {
  const out: ProbeDrift[] = [];
  const names = [
    ...new Set([...Object.keys(before?.probes ?? {}), ...Object.keys(after.probes)]),
  ].sort();
  for (const name of names) {
    const b = before?.probes[name];
    const a = after.probes[name];
    const statusChanges: string[] = [];
    if (!b) statusChanges.push('probe is new (no committed entry)');
    else if (!a) statusChanges.push('probe missing from fresh run');
    else {
      if (b.status !== a.status) statusChanges.push(`status ${b.status} → ${a.status}`);
      if (b.httpStatus !== a.httpStatus)
        statusChanges.push(`httpStatus ${b.httpStatus ?? '-'} → ${a.httpStatus ?? '-'}`);
      if (b.errorCode !== a.errorCode)
        statusChanges.push(`errorCode ${b.errorCode ?? '-'} → ${a.errorCode ?? '-'}`);
    }
    const shapeDiffs = b && a ? diffShapes(b.shape, a.shape) : [];
    // A committed entry without `wire` predates wire capture: "no baseline yet", not drift.
    const wire = b && a ? diffWire(b.wire, a.wire) : NO_WIRE_CHANGE;
    if (statusChanges.length || shapeDiffs.length || hasWireDiff(wire))
      out.push({ probe: name, statusChanges, shapeDiffs, wire });
  }
  return out;
}

function hasWireDiff(w: WireDiff): boolean {
  return w.baseline === 'present' && (w.changes.length > 0 || w.shapeDiffs.length > 0);
}

function isSdkBlocking(d: ProbeDrift): boolean {
  return d.statusChanges.length > 0 || d.shapeDiffs.some((x) => x.kind !== 'nullability');
}

function isWireBlocking(w: WireDiff): boolean {
  return (
    w.baseline === 'present' &&
    (w.changes.length > 0 || w.shapeDiffs.some((x) => x.kind !== 'nullability'))
  );
}

function isBlocking(d: ProbeDrift): boolean {
  return isSdkBlocking(d) || isWireBlocking(d.wire);
}

/** Probes whose committed entry has no `wire` list yet (snapshot predates wire capture). */
function probesWithoutWireBaseline(before: Snapshot): string[] {
  return Object.entries(before.probes)
    .filter(([, p]) => p.wire === undefined)
    .map(([name]) => name)
    .sort();
}

// ─── Reporting ──────────────────────────────────────────────────────────────

function printTable(set: ProbeSet<unknown>, results: ProbeResult[]): void {
  const w = Math.max(...results.map((r) => r.name.length), 8);
  console.log(`\n${set.marketplace} (${set.envLabel()})`);
  console.log(`  ${'probe'.padEnd(w)}  status   http  ms     shape`);
  for (const r of results) {
    const icon = r.status === 'ok' ? '✓' : r.status === 'error' ? '✖' : '–';
    const detail =
      r.status === 'ok' && r.shape
        ? describe(r.shape)
        : r.status === 'error'
          ? `${r.errorName ?? ''}${r.errorCode ? ` ${r.errorCode}` : ''}`
          : 'skipped (no credentials)';
    console.log(
      `  ${r.name.padEnd(w)}  ${icon} ${r.status.padEnd(7)} ${String(r.httpStatus ?? '').padStart(4)}  ${String(r.durationMs).padStart(5)}  ${detail}`,
    );
  }
  const wire = results.flatMap((r) => r.wire ?? []);
  if (wire.length) {
    const operations = new Set(wire.map((x) => x.operation.key));
    const unmatched = new Set(
      wire.filter((x) => isUnmatched(x.operation)).map((x) => x.operation.key),
    );
    console.log(
      `  wire: ${operations.size} operation(s)${unmatched.size ? `, ${unmatched.size} with no spec match` : ''}`,
    );
  }
}

function formatShapeDiff(x: ShapeDiff): string {
  const arrow = x.from && x.to ? `${x.from} → ${x.to}` : (x.to ?? x.from ?? '');
  return `- \`${x.path}\` ${x.kind}${arrow ? `: ${arrow}` : ''}`;
}

interface ReportEntry {
  set: ProbeSet<unknown>;
  drift: ProbeDrift[];
  missingSnapshot: boolean;
  /** Probes whose committed entry has no `wire` baseline yet. */
  noWireBaseline: string[];
}

function renderReport(entries: ReportEntry[]): string {
  const lines: string[] = ['# Contract probe report', ''];
  for (const { set, drift, missingSnapshot, noWireBaseline } of entries) {
    lines.push(`## ${set.marketplace} (${set.envLabel()})`, '');
    if (missingSnapshot) {
      lines.push(
        `No committed snapshot at \`probe-snapshots/${set.marketplace}.json\` — run \`pnpm probe\` and commit it.`,
        '',
      );
      continue;
    }
    if (noWireBaseline.length) {
      lines.push(
        `No wire baseline yet for ${noWireBaseline.length} probe(s) (the snapshot predates wire capture), so wire drift was not checked for them. Run \`pnpm probe\` to record one.`,
        '',
      );
    }
    if (drift.length === 0) {
      lines.push('No drift.', '');
      continue;
    }
    const sdkDrift = drift.filter((d) => d.statusChanges.length || d.shapeDiffs.length);
    lines.push('### SDK output', '', ...(sdkDrift.length ? [] : ['No drift.', '']));
    for (const d of sdkDrift) {
      lines.push(`#### \`${d.probe}\`${isSdkBlocking(d) ? '' : ' (informational)'}`, '');
      for (const s of d.statusChanges) lines.push(`- ${s}`);
      for (const x of d.shapeDiffs) lines.push(formatShapeDiff(x));
      lines.push('');
    }
    const wireDrift = drift.filter((d) => hasWireDiff(d.wire));
    lines.push('### Wire (raw responses)', '', ...(wireDrift.length ? [] : ['No drift.', '']));
    for (const d of wireDrift) {
      if (d.wire.baseline !== 'present') continue;
      lines.push(`#### \`${d.probe}\`${isWireBlocking(d.wire) ? '' : ' (informational)'}`, '');
      for (const c of d.wire.changes) lines.push(`- ${c}`);
      for (const x of d.wire.shapeDiffs) lines.push(formatShapeDiff(x));
      lines.push('');
    }
  }
  return lines.join('\n');
}

// ─── Main ───────────────────────────────────────────────────────────────────

let exitCode = 0;
const reportEntries: ReportEntry[] = [];
// Spec index for wire capture: each recorded request is reduced to the
// documented operation it hit (path template), never to its concrete URL.
const SPEC_INDEX = buildOperationIndex(loadSpecs(join(REPO_ROOT, 'specs')));
const summary: Record<string, { ok: number; error: number; skipped: number }> = {};

for (const set of selected) {
  const results: ProbeResult[] = [];
  if (!hasCredentials(set)) {
    for (const probe of set.probes) results.push(skippedResult(set, probe));
    printTable(set, results);
    summary[set.marketplace] = { ok: 0, error: 0, skipped: results.length };
    if (flags['require-credentials']) {
      console.error(
        `✖ ${set.marketplace}: credentials missing (${set.requiredEnv.join(', ')}) and --require-credentials is set`,
      );
      exitCode = 2;
    }
    continue;
  }

  // The SDK factories take no `fetch` option, but both transports bind
  // `fetch` when they are constructed — so build the client while the
  // recorder is the global fetch (restored right after). SDK code and
  // behaviour are unchanged; the recorder reads bodies from a clone.
  const recorder = createWireRecorder({
    index: SPEC_INDEX,
    summarizeOptions: DEFAULT_SUMMARIZE_OPTIONS,
  });
  const client = withGlobalFetch(recorder.fetch, () => set.createClient());
  for (const probe of set.probes) {
    results.push(await runProbe(set, probe, client, DEFAULT_SUMMARIZE_OPTIONS, recorder));
  }
  printTable(set, results);
  summary[set.marketplace] = {
    ok: results.filter((r) => r.status === 'ok').length,
    error: results.filter((r) => r.status === 'error').length,
    skipped: 0,
  };

  const fresh = toSnapshot(set, results);
  writeJson(join(OUT_DIR, `${set.marketplace}.json`), fresh);
  writeJson(
    join(OUT_DIR, `${set.marketplace}.timings.json`),
    Object.fromEntries(results.map((r) => [r.name, r.durationMs])),
  );

  if (MODE === 'update') {
    writeJson(join(SNAPSHOT_DIR, `${set.marketplace}.json`), fresh);
    console.log(`  → wrote probe-snapshots/${set.marketplace}.json`);
    continue;
  }

  const committed = readSnapshot(set.marketplace);
  const drift = committed ? driftFor(committed, fresh) : [];
  if (committed && committed.env !== fresh.env) {
    // Comparing a `stage` baseline with a `prod` run (or vice versa) is not a
    // contract signal; surface it as its own blocking entry.
    drift.unshift({
      probe: '(environment)',
      statusChanges: [
        `snapshot env ${committed.env} → current env ${fresh.env}; regenerate with \`pnpm probe --only ${set.marketplace}\``,
      ],
      shapeDiffs: [],
      wire: NO_WIRE_CHANGE,
    });
  }
  const noWireBaseline = committed ? probesWithoutWireBaseline(committed) : [];
  if (noWireBaseline.length) {
    console.log(
      `  ! no wire baseline yet for ${noWireBaseline.length} probe(s) — the snapshot predates wire capture; run \`pnpm probe\` to record one (not treated as drift)`,
    );
  }
  if (committed && !Object.values(committed.probes).some((p) => p.status === 'ok')) {
    console.log(
      `  ! committed snapshot has no successful probe — baseline is a placeholder, regenerate it from a working environment`,
    );
  }
  reportEntries.push({ set, drift, missingSnapshot: !committed, noWireBaseline });
  if (!committed) {
    console.log(`  ✖ no committed snapshot for ${set.marketplace} — run \`pnpm probe\` first`);
    exitCode = Math.max(exitCode, 1);
  } else if (drift.some(isBlocking)) {
    console.log(`  ✖ drift detected in ${drift.filter(isBlocking).length} probe(s)`);
    exitCode = Math.max(exitCode, 1);
  } else {
    console.log(
      drift.length
        ? `  ✓ no drift (${drift.length} informational nullability note(s))`
        : '  ✓ no drift',
    );
  }
}

writeJson(join(OUT_DIR, 'summary.json'), { mode: MODE, summary });

if (MODE === 'check') {
  const report = renderReport(reportEntries);
  mkdirSync(OUT_DIR, { recursive: true });
  writeFileSync(join(OUT_DIR, 'report.md'), `${report}\n`, 'utf8');
  if (exitCode === 1) console.log(`\n${report}`);
}

console.log(
  `\n${Object.entries(summary)
    .map(([m, s]) => `${m}: ${s.ok} ok / ${s.error} error / ${s.skipped} skipped`)
    .join('   ')}`,
);
process.exit(exitCode);
